- name: Hello World Sample
  hosts: all
  vars:
    message: "Hello World!"
    pauseInSec: 0
  tasks:
    - name: Hello Message
      debug:
        msg: "{{ message }}"
    - pause:
        seconds: "{{ pauseInSec }}"